version: '3.8'

services:
  db:
    image: postgres:17-alpine  # Using the Alpine version of PostgreSQL 14
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: LEARNING_JOURNEY
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin           # pgAdmin login password
    ports:
      - "8080:80"  # Access pgAdmin at http://localhost:8080
    depends_on:
      - db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
